
// This file was automatically generated by the Dapper.FastCRUD T4 Template
// Do not make changes directly to this file - edit the template configuration instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `Connection`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source=192.168.30.187;Initial Catalog=DTrmsdb;uid=cctv;pwd=123456`
//     Include Views:          `True`

namespace CannyData.Models
{
	using System;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using System.Collections.Generic;

    /// <summary>
    /// A class which represents the by_user_etor table.
    /// </summary>
	[Table("by_user_etor")]
	public partial class byuseretor
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int id { get; set; }
	    public virtual int? user_id { get; set; }
	    public virtual int? etor_id { get; set; }
	    public virtual DateTime? create_time { get; set; }
	    public virtual int? create_userid { get; set; }
	    public virtual string field_1 { get; set; }
	    public virtual string field_2 { get; set; }
	}

    /// <summary>
    /// A class which represents the by_v_dtu_detail view.
    /// </summary>
	[Table("by_v_dtu_detail")]
	public partial class byvdtudetail
	{
	    public virtual int id { get; set; }
	    public virtual string bianhao { get; set; }
	    public virtual byte status { get; set; }
	    public virtual DateTime? status_time { get; set; }
	    public virtual string version { get; set; }
	    public virtual DateTime? veision_time { get; set; }
	    public virtual string rssi { get; set; }
	    public virtual DateTime? rssi_time { get; set; }
	    public virtual string ip { get; set; }
	    public virtual DateTime? lastactive_time { get; set; }
	    public virtual string imei { get; set; }
	    public virtual string imsi { get; set; }
	    public virtual DateTime? create_time { get; set; }
	    public virtual byte? is_statusAsk { get; set; }
	    public virtual DateTime? statusAsk_endtime { get; set; }
	    public virtual int? heartbeat_interval { get; set; }
	    public virtual string server_ip { get; set; }
	    public virtual string server_port_canny { get; set; }
	    public virtual string server_port_byline { get; set; }
	    public virtual int? create_userid { get; set; }
	    public virtual string etor_bianhao { get; set; }
	    public virtual int? etor_species_id { get; set; }
	    public virtual int? project_id { get; set; }
	    public virtual int? organize_id { get; set; }
	    public virtual string dizhi_code { get; set; }
	    public virtual string build_name { get; set; }
	    public virtual string build_number { get; set; }
	    public virtual string build_etorindex { get; set; }
	    public virtual string dizhi_detail { get; set; }
	    public virtual string zuobiao { get; set; }
	    public virtual string zhuban_code { get; set; }
	    public virtual string zhuban_version { get; set; }
	    public virtual DateTime? zhuban_version_time { get; set; }
	    public virtual string floorcount { get; set; }
	    public virtual string weibao_user { get; set; }
	    public virtual string weibao_userphone { get; set; }
	    public virtual string weibao_manager { get; set; }
	    public virtual string weibao_managerphone { get; set; }
	    public virtual string weibao_interval { get; set; }
	    public virtual string weibao_type { get; set; }
	    public virtual string nianjian_time { get; set; }
	    public virtual string use_place { get; set; }
	    public virtual string brand_id { get; set; }
	    public virtual string etor_model { get; set; }
	    public virtual string product_model { get; set; }
	    public virtual string etor_field_1 { get; set; }
	    public virtual string etor_field_2 { get; set; }
	    public virtual string sim_id { get; set; }
	}

    /// <summary>
    /// A class which represents the by_organize table.
    /// </summary>
	[Table("by_organize")]
	public partial class byorganize
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int id { get; set; }
	    public virtual int? parent_id { get; set; }
	    public virtual string bianhao { get; set; }
	    public virtual string name { get; set; }
	    public virtual string type { get; set; }
	    public virtual string manager_master { get; set; }
	    public virtual string manager_master_phone { get; set; }
	    public virtual string manager_second { get; set; }
	    public virtual string manager_second_phone { get; set; }
	    public virtual string fax { get; set; }
	    public virtual string zipcode { get; set; }
	    public virtual string caption { get; set; }
	    public virtual string dizhi_code { get; set; }
	    public virtual string dizhi_detail { get; set; }
	    public virtual byte? enabled { get; set; }
	    public virtual int? sort_id { get; set; }
	    public virtual DateTime? create_time { get; set; }
	    public virtual int? create_userid { get; set; }
	    public virtual string field_1 { get; set; }
	    public virtual string field_2 { get; set; }
	}

    /// <summary>
    /// A class which represents the by_dtu table.
    /// </summary>
	[Table("by_dtu")]
	public partial class bydtu
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int id { get; set; }
	    public virtual string bianhao { get; set; }
	    public virtual byte status { get; set; }
	    public virtual DateTime? status_time { get; set; }
	    public virtual string version { get; set; }
	    public virtual DateTime? veision_time { get; set; }
	    public virtual string rssi { get; set; }
	    public virtual DateTime? rssi_time { get; set; }
	    public virtual string ip { get; set; }
	    public virtual DateTime? lastactive_time { get; set; }
	    public virtual string imei { get; set; }
	    public virtual string imsi { get; set; }
	    public virtual string sim { get; set; }
	    public virtual DateTime? create_time { get; set; }
	    public virtual byte? is_statusAsk { get; set; }
	    public virtual DateTime? statusAsk_endtime { get; set; }
	    public virtual int? heartbeat_interval { get; set; }
	    public virtual string server_ip { get; set; }
	    public virtual string server_port_canny { get; set; }
	    public virtual string server_port_byline { get; set; }
	    public virtual int? create_userid { get; set; }
	    public virtual string field_1 { get; set; }
	    public virtual string field_2 { get; set; }
	}

    /// <summary>
    /// A class which represents the by_user table.
    /// </summary>
	[Table("by_user")]
	public partial class byuser
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int id { get; set; }
	    public virtual string bianhao { get; set; }
	    public virtual string account { get; set; }
	    public virtual string pwd { get; set; }
	    public virtual string secre_key { get; set; }
	    public virtual byte? user_type { get; set; }
	    public virtual string realname { get; set; }
	    public virtual string realname_spell { get; set; }
	    public virtual string sub_name { get; set; }
	    public virtual int? role_id { get; set; }
	    public virtual int? organize_id { get; set; }
	    public virtual byte? sex { get; set; }
	    public virtual string title { get; set; }
	    public virtual string email { get; set; }
	    public virtual string phone { get; set; }
	    public virtual string caption { get; set; }
	    public virtual byte? enabled { get; set; }
	    public virtual byte? single_login { get; set; }
	    public virtual byte? mobile_login { get; set; }
	    public virtual byte? is_limitip { get; set; }
	    public virtual byte? is_alarm { get; set; }
	    public virtual byte? is_sys { get; set; }
	    public virtual DateTime? create_time { get; set; }
	    public virtual int? create_userid { get; set; }
	    public virtual string remark { get; set; }
	    public virtual string field_1 { get; set; }
	    public virtual string field_2 { get; set; }
	    public virtual string field_3 { get; set; }
	}

    /// <summary>
    /// A class which represents the by_v_dtu_disconn_detail view.
    /// </summary>
	[Table("by_v_dtu_disconn_detail")]
	public partial class byvdtudisconndetail
	{
	    public virtual int id { get; set; }
	    public virtual int? dtu_id { get; set; }
	    public virtual int? etor_id { get; set; }
	    public virtual byte? type { get; set; }
	    public virtual string start_time { get; set; }
	    public virtual string end_time { get; set; }
	    public virtual string field_1 { get; set; }
	    public virtual string field_2 { get; set; }
	    public virtual string bianhao { get; set; }
	    public virtual byte? status { get; set; }
	    public virtual DateTime? status_time { get; set; }
	    public virtual string version { get; set; }
	    public virtual DateTime? veision_time { get; set; }
	    public virtual string rssi { get; set; }
	    public virtual DateTime? rssi_time { get; set; }
	    public virtual string ip { get; set; }
	    public virtual DateTime? lastactive_time { get; set; }
	    public virtual string imei { get; set; }
	    public virtual string imsi { get; set; }
	    public virtual string sim { get; set; }
	    public virtual DateTime? dtu_create_time { get; set; }
	    public virtual byte? is_statusAsk { get; set; }
	    public virtual DateTime? statusAsk_endtime { get; set; }
	    public virtual int? heartbeat_interval { get; set; }
	    public virtual string server_ip { get; set; }
	    public virtual string server_port_canny { get; set; }
	    public virtual string server_port_byline { get; set; }
	    public virtual string etor_bianhao { get; set; }
	    public virtual int? etor_species_id { get; set; }
	    public virtual int? project_id { get; set; }
	    public virtual int? organize_id { get; set; }
	    public virtual string dizhi_code { get; set; }
	    public virtual string build_name { get; set; }
	    public virtual string build_number { get; set; }
	    public virtual string build_etorindex { get; set; }
	    public virtual string dizhi_detail { get; set; }
	    public virtual string zuobiao { get; set; }
	    public virtual string zhuban_code { get; set; }
	    public virtual string zhuban_version { get; set; }
	    public virtual DateTime? zhuban_version_time { get; set; }
	    public virtual string floorcount { get; set; }
	    public virtual string weibao_user { get; set; }
	    public virtual string weibao_userphone { get; set; }
	    public virtual string weibao_manager { get; set; }
	    public virtual string weibao_managerphone { get; set; }
	    public virtual string weibao_interval { get; set; }
	    public virtual string weibao_type { get; set; }
	    public virtual string nianjian_time { get; set; }
	    public virtual string use_place { get; set; }
	    public virtual string brand_id { get; set; }
	    public virtual string etor_model { get; set; }
	    public virtual string product_model { get; set; }
	}

    /// <summary>
    /// A class which represents the by_dictionary table.
    /// </summary>
	[Table("by_dictionary")]
	public partial class bydictionary
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int id { get; set; }
	    public virtual string dic_name { get; set; }
	    public virtual string dic_key { get; set; }
	    public virtual string dic_value { get; set; }
	    public virtual int? sort_id { get; set; }
	    public virtual string field_1 { get; set; }
	    public virtual string field_2 { get; set; }
	}

    /// <summary>
    /// A class which represents the by_etor_species table.
    /// </summary>
	[Table("by_etor_species")]
	public partial class byetorspecy
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int id { get; set; }
	    public virtual string code { get; set; }
	    public virtual string caption { get; set; }
	    public virtual byte? etor_type { get; set; }
	    public virtual string etor_default_img { get; set; }
	    public virtual string remote_aspx { get; set; }
	    public virtual string fault_index_depth { get; set; }
	    public virtual string fault_time_format { get; set; }
	    public virtual string mask_format { get; set; }
	    public virtual string mask_time_unit { get; set; }
	    public virtual string field_1 { get; set; }
	    public virtual string field_2 { get; set; }
	}

    /// <summary>
    /// A class which represents the by_user_role table.
    /// </summary>
	[Table("by_user_role")]
	public partial class byuserrole
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int id { get; set; }
	    public virtual int? user_id { get; set; }
	    public virtual int? role_id { get; set; }
	    public virtual DateTime? create_time { get; set; }
	    public virtual int? create_userid { get; set; }
	    public virtual string field_1 { get; set; }
	    public virtual string field_2 { get; set; }
	}

    /// <summary>
    /// A class which represents the by_etor_mask_log table.
    /// </summary>
	[Table("by_etor_mask_log")]
	public partial class byetormasklog
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual long id { get; set; }
	    public virtual int etor_id { get; set; }
	    public virtual DateTime? mask_time { get; set; }
	    public virtual string mask_runtime { get; set; }
	    public virtual string mask_runcount { get; set; }
	    public virtual string mask_faultcount { get; set; }
	    public virtual string field_1 { get; set; }
	    public virtual string field_2 { get; set; }
	    public virtual string field_3 { get; set; }
	    public virtual string field_4 { get; set; }
	    public virtual string field_5 { get; set; }
	}

    /// <summary>
    /// A class which represents the by_user_organize table.
    /// </summary>
	[Table("by_user_organize")]
	public partial class byuserorganize
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int id { get; set; }
	    public virtual int? user_id { get; set; }
	    public virtual int? organize_id { get; set; }
	    public virtual DateTime? create_time { get; set; }
	    public virtual int? create_userid { get; set; }
	    public virtual string field_1 { get; set; }
	    public virtual string field_2 { get; set; }
	}

    /// <summary>
    /// A class which represents the by_v_tickets_turnup view.
    /// </summary>
	[Table("by_v_tickets_turnup")]
	public partial class byvticketsturnup
	{
	    public virtual int id { get; set; }
	    public virtual int? etor_tickets_id { get; set; }
	    public virtual byte? step_index { get; set; }
	    public virtual string step_name { get; set; }
	    public virtual byte? step_status { get; set; }
	    public virtual string step_time { get; set; }
	    public virtual string field_1 { get; set; }
	    public virtual string field_2 { get; set; }
	    public virtual int? etor_id { get; set; }
	    public virtual string bianhao { get; set; }
	    public virtual int? status { get; set; }
	    public virtual int? type { get; set; }
	    public virtual int? call_user { get; set; }
	    public virtual string call_content { get; set; }
	    public virtual string call_type { get; set; }
	    public virtual string receive_user { get; set; }
	    public virtual string receive_userphone { get; set; }
	    public virtual DateTime? create_time { get; set; }
	    public virtual string remark { get; set; }
	    public virtual byte? is_inspection { get; set; }
	    public virtual string etor_bianhao { get; set; }
	    public virtual int dtu_id { get; set; }
	    public virtual int? etor_species_id { get; set; }
	    public virtual int? project_id { get; set; }
	    public virtual int? organize_id { get; set; }
	    public virtual string dizhi_code { get; set; }
	    public virtual string build_name { get; set; }
	    public virtual string build_number { get; set; }
	    public virtual string build_etorindex { get; set; }
	    public virtual string dizhi_detail { get; set; }
	    public virtual string zuobiao { get; set; }
	    public virtual string zhuban_code { get; set; }
	    public virtual string zhuban_version { get; set; }
	    public virtual DateTime? zhuban_version_time { get; set; }
	    public virtual string floorcount { get; set; }
	    public virtual string weibao_user { get; set; }
	    public virtual string weibao_userphone { get; set; }
	    public virtual string weibao_manager { get; set; }
	    public virtual string weibao_managerphone { get; set; }
	    public virtual string weibao_interval { get; set; }
	    public virtual string weibao_type { get; set; }
	    public virtual string nianjian_time { get; set; }
	    public virtual string use_place { get; set; }
	    public virtual string brand_id { get; set; }
	    public virtual string etor_model { get; set; }
	    public virtual string product_model { get; set; }
	    public virtual int? rate { get; set; }
	}

    /// <summary>
    /// A class which represents the by_v_etor_fault_config_detail view.
    /// </summary>
	[Table("by_v_etor_fault_config_detail")]
	public partial class byvetorfaultconfigdetail
	{
	    public virtual int id { get; set; }
	    public virtual int? etor_species_id { get; set; }
	    public virtual string fault_code { get; set; }
	    public virtual string fault_display_code { get; set; }
	    public virtual string fault_desc { get; set; }
	    public virtual string fault_desc_en { get; set; }
	    public virtual byte? is_alarm { get; set; }
	    public virtual int? sms_delay { get; set; }
	    public virtual string sms_desc { get; set; }
	    public virtual string sms_desc_en { get; set; }
	    public virtual string type { get; set; }
	    public virtual string levels { get; set; }
	    public virtual string sleep_starttime { get; set; }
	    public virtual string sleep_endtime { get; set; }
	    public virtual string field_1 { get; set; }
	    public virtual string field_2 { get; set; }
	    public virtual string code { get; set; }
	    public virtual string caption { get; set; }
	    public virtual byte? etor_type { get; set; }
	    public virtual string etor_default_img { get; set; }
	    public virtual string remote_aspx { get; set; }
	    public virtual string fault_index_depth { get; set; }
	    public virtual string mask_format { get; set; }
	    public virtual string species_field_1 { get; set; }
	    public virtual string species_field_2 { get; set; }
	}

    /// <summary>
    /// A class which represents the by_v_tickets_fault_detail view.
    /// </summary>
	[Table("by_v_tickets_fault_detail")]
	public partial class byvticketsfaultdetail
	{
	    public virtual int id { get; set; }
	    public virtual int? etor_tickets_id { get; set; }
	    public virtual int? etor_id { get; set; }
	    public virtual string dtu_bianhao { get; set; }
	    public virtual string master_code { get; set; }
	    public virtual string second_code { get; set; }
	    public virtual string fault_speed { get; set; }
	    public virtual string fault_floor { get; set; }
	    public virtual string fault_datetime { get; set; }
	    public virtual string fault_content { get; set; }
	    public virtual string remark { get; set; }
	    public virtual DateTime? create_time { get; set; }
	    public virtual string field_1 { get; set; }
	    public virtual string field_2 { get; set; }
	    public virtual string field_3 { get; set; }
	    public virtual string field_4 { get; set; }
	    public virtual string field_5 { get; set; }
	    public virtual string etor_bianhao { get; set; }
	    public virtual int? dtu_id { get; set; }
	    public virtual int? etor_species_id { get; set; }
	    public virtual int? project_id { get; set; }
	    public virtual int? organize_id { get; set; }
	    public virtual string dizhi_code { get; set; }
	    public virtual string build_name { get; set; }
	    public virtual string build_number { get; set; }
	    public virtual string build_etorindex { get; set; }
	    public virtual string dizhi_detail { get; set; }
	    public virtual string zuobiao { get; set; }
	    public virtual string zhuban_code { get; set; }
	    public virtual string zhuban_version { get; set; }
	    public virtual DateTime? zhuban_version_time { get; set; }
	    public virtual string floorcount { get; set; }
	    public virtual string weibao_user { get; set; }
	    public virtual string weibao_userphone { get; set; }
	    public virtual string weibao_manager { get; set; }
	    public virtual string weibao_managerphone { get; set; }
	    public virtual string weibao_interval { get; set; }
	    public virtual string weibao_type { get; set; }
	    public virtual string nianjian_time { get; set; }
	    public virtual string use_place { get; set; }
	    public virtual string brand_id { get; set; }
	    public virtual string etor_model { get; set; }
	    public virtual string product_model { get; set; }
	    public virtual string fault_code { get; set; }
	    public virtual string fault_display_code { get; set; }
	    public virtual string fault_desc { get; set; }
	    public virtual string fault_desc_en { get; set; }
	    public virtual byte? is_alarm { get; set; }
	    public virtual int? sms_delay { get; set; }
	    public virtual string sms_desc { get; set; }
	    public virtual string sms_desc_en { get; set; }
	    public virtual string type { get; set; }
	    public virtual string levels { get; set; }
	    public virtual string sleep_starttime { get; set; }
	    public virtual string sleep_endtime { get; set; }
	    public virtual string etor_species_caption { get; set; }
	    public virtual string etor_species_code { get; set; }
	    public virtual byte? etor_type { get; set; }
	    public virtual string remote_aspx { get; set; }
	    public virtual string etor_default_img { get; set; }
	    public virtual string mask_format { get; set; }
	}

    /// <summary>
    /// A class which represents the by_v_tickets_detail view.
    /// </summary>
	[Table("by_v_tickets_detail")]
	public partial class byvticketsdetail
	{
	    public virtual int id { get; set; }
	    public virtual int? etor_id { get; set; }
	    public virtual string bianhao { get; set; }
	    public virtual int? status { get; set; }
	    public virtual int? type { get; set; }
	    public virtual int? call_user { get; set; }
	    public virtual string call_content { get; set; }
	    public virtual string call_type { get; set; }
	    public virtual string receive_user { get; set; }
	    public virtual string receive_userphone { get; set; }
	    public virtual DateTime? create_time { get; set; }
	    public virtual string remark { get; set; }
	    public virtual byte? is_inspection { get; set; }
	    public virtual string field_1 { get; set; }
	    public virtual string field_2 { get; set; }
	    public virtual string dtu_bianhao { get; set; }
	    public virtual string etor_bianhao { get; set; }
	    public virtual int dtu_id { get; set; }
	    public virtual int? etor_species_id { get; set; }
	    public virtual int? project_id { get; set; }
	    public virtual int? organize_id { get; set; }
	    public virtual string dizhi_code { get; set; }
	    public virtual string build_name { get; set; }
	    public virtual string build_number { get; set; }
	    public virtual string build_etorindex { get; set; }
	    public virtual string dizhi_detail { get; set; }
	    public virtual string zuobiao { get; set; }
	    public virtual string zhuban_code { get; set; }
	    public virtual string zhuban_version { get; set; }
	    public virtual DateTime? zhuban_version_time { get; set; }
	    public virtual string floorcount { get; set; }
	    public virtual string weibao_user { get; set; }
	    public virtual string weibao_userphone { get; set; }
	    public virtual string weibao_manager { get; set; }
	    public virtual string weibao_managerphone { get; set; }
	    public virtual string weibao_interval { get; set; }
	    public virtual string weibao_type { get; set; }
	    public virtual string nianjian_time { get; set; }
	    public virtual string use_place { get; set; }
	    public virtual string brand_id { get; set; }
	    public virtual string etor_model { get; set; }
	    public virtual string product_model { get; set; }
	    public virtual string fault_code { get; set; }
	    public virtual string fault_display_code { get; set; }
	    public virtual string fault_desc { get; set; }
	    public virtual string fault_desc_en { get; set; }
	    public virtual byte? is_alarm { get; set; }
	    public virtual int? sms_delay { get; set; }
	    public virtual string sms_desc { get; set; }
	    public virtual string sms_desc_en { get; set; }
	    public virtual string fault_config_type { get; set; }
	    public virtual string levels { get; set; }
	    public virtual string sleep_starttime { get; set; }
	    public virtual string sleep_endtime { get; set; }
	    public virtual string remote_aspx { get; set; }
	}

    /// <summary>
    /// A class which represents the by_dtu_disconn table.
    /// </summary>
	[Table("by_dtu_disconn")]
	public partial class bydtudisconn
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int id { get; set; }
	    public virtual int? dtu_id { get; set; }
	    public virtual int? etor_id { get; set; }
	    public virtual byte? type { get; set; }
	    public virtual string start_time { get; set; }
	    public virtual string end_time { get; set; }
	    public virtual string field_1 { get; set; }
	    public virtual string field_2 { get; set; }
	}

    /// <summary>
    /// A class which represents the by_login_log table.
    /// </summary>
	[Table("by_login_log")]
	public partial class byloginlog
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int id { get; set; }
	    public virtual string account { get; set; }
	    public virtual string status { get; set; }
	    public virtual string ip_address { get; set; }
	    public virtual string mac_address { get; set; }
	    public virtual string login_device { get; set; }
	    public virtual string browser_version { get; set; }
	    public virtual DateTime? create_time { get; set; }
	    public virtual string field_1 { get; set; }
	    public virtual string field_2 { get; set; }
	}

    /// <summary>
    /// A class which represents the by_v_dc_etor_detail view.
    /// </summary>
	[Table("by_v_dc_etor_detail")]
	public partial class byvdcetordetail
	{
	    public virtual int id { get; set; }
	    public virtual string bianhao { get; set; }
	    public virtual int dtu_id { get; set; }
	    public virtual int? etor_species_id { get; set; }
	    public virtual int? project_id { get; set; }
	    public virtual int? organize_id { get; set; }
	    public virtual string dizhi_code { get; set; }
	    public virtual string build_name { get; set; }
	    public virtual string build_number { get; set; }
	    public virtual string build_etorindex { get; set; }
	    public virtual string dizhi_detail { get; set; }
	    public virtual string zuobiao { get; set; }
	    public virtual string zhuban_code { get; set; }
	    public virtual string zhuban_version { get; set; }
	    public virtual DateTime? zhuban_version_time { get; set; }
	    public virtual string floorcount { get; set; }
	    public virtual string weibao_user { get; set; }
	    public virtual string weibao_userphone { get; set; }
	    public virtual string weibao_manager { get; set; }
	    public virtual string weibao_managerphone { get; set; }
	    public virtual string weibao_interval { get; set; }
	    public virtual string weibao_type { get; set; }
	    public virtual string nianjian_time { get; set; }
	    public virtual string use_place { get; set; }
	    public virtual string brand_id { get; set; }
	    public virtual string etor_model { get; set; }
	    public virtual string product_model { get; set; }
	    public virtual int? create_userid { get; set; }
	    public virtual DateTime? create_time { get; set; }
	    public virtual string dtu_bianhao { get; set; }
	    public virtual byte? status { get; set; }
	    public virtual DateTime? status_time { get; set; }
	    public virtual string version { get; set; }
	    public virtual DateTime? veision_time { get; set; }
	    public virtual string rssi { get; set; }
	    public virtual DateTime? rssi_time { get; set; }
	    public virtual string ip { get; set; }
	    public virtual DateTime? lastactive_time { get; set; }
	    public virtual string imei { get; set; }
	    public virtual string imsi { get; set; }
	    public virtual string sim { get; set; }
	    public virtual DateTime? dtu_create_time { get; set; }
	    public virtual byte? is_statusAsk { get; set; }
	    public virtual DateTime? statusAsk_endtime { get; set; }
	    public virtual int? heartbeat_interval { get; set; }
	    public virtual string etor_species_code { get; set; }
	    public virtual string caption { get; set; }
	    public virtual byte? etor_type { get; set; }
	    public virtual string etor_default_img { get; set; }
	    public virtual string remote_aspx { get; set; }
	    public virtual string fault_index_depth { get; set; }
	    public virtual string mask_format { get; set; }
	    public virtual string project_bianhao { get; set; }
	    public virtual string project_name { get; set; }
	    public virtual string organize_bianhao { get; set; }
	    public virtual string organize_name { get; set; }
	    public virtual string sheng { get; set; }
	    public virtual string shi { get; set; }
	    public virtual string quxian { get; set; }
	    public virtual int? ticket_count { get; set; }
	    public virtual int? ticket_fault_count { get; set; }
	    public virtual string Mask_1 { get; set; }
	    public virtual string Mask_2 { get; set; }
	    public virtual string Mask_3 { get; set; }
	}

    /// <summary>
    /// A class which represents the by_v_tickets_duce view.
    /// </summary>
	[Table("by_v_tickets_duce")]
	public partial class byvticketsduce
	{
	    public virtual int id { get; set; }
	    public virtual int? etor_id { get; set; }
	    public virtual string bianhao { get; set; }
	    public virtual int? status { get; set; }
	    public virtual int? type { get; set; }
	    public virtual int? call_user { get; set; }
	    public virtual string call_content { get; set; }
	    public virtual string call_type { get; set; }
	    public virtual string receive_user { get; set; }
	    public virtual string receive_userphone { get; set; }
	    public virtual DateTime? create_time { get; set; }
	    public virtual string remark { get; set; }
	    public virtual byte? is_inspection { get; set; }
	    public virtual string field_1 { get; set; }
	    public virtual string field_2 { get; set; }
	    public virtual string dtu_bianhao { get; set; }
	    public virtual string etor_bianhao { get; set; }
	    public virtual int dtu_id { get; set; }
	    public virtual int? etor_species_id { get; set; }
	    public virtual int? project_id { get; set; }
	    public virtual int? organize_id { get; set; }
	    public virtual string dizhi_code { get; set; }
	    public virtual string build_name { get; set; }
	    public virtual string build_number { get; set; }
	    public virtual string build_etorindex { get; set; }
	    public virtual string dizhi_detail { get; set; }
	    public virtual string zuobiao { get; set; }
	    public virtual string zhuban_code { get; set; }
	    public virtual string zhuban_version { get; set; }
	    public virtual DateTime? zhuban_version_time { get; set; }
	    public virtual string floorcount { get; set; }
	    public virtual string weibao_user { get; set; }
	    public virtual string weibao_userphone { get; set; }
	    public virtual string weibao_manager { get; set; }
	    public virtual string weibao_managerphone { get; set; }
	    public virtual string weibao_interval { get; set; }
	    public virtual string weibao_type { get; set; }
	    public virtual string nianjian_time { get; set; }
	    public virtual string use_place { get; set; }
	    public virtual string brand_id { get; set; }
	    public virtual string etor_model { get; set; }
	    public virtual string product_model { get; set; }
	    public virtual string fault_code { get; set; }
	    public virtual string fault_display_code { get; set; }
	    public virtual string fault_desc { get; set; }
	    public virtual string fault_desc_en { get; set; }
	    public virtual byte? is_alarm { get; set; }
	    public virtual int? sms_delay { get; set; }
	    public virtual string sms_desc { get; set; }
	    public virtual string sms_desc_en { get; set; }
	    public virtual string fault_config_type { get; set; }
	    public virtual string levels { get; set; }
	    public virtual string sleep_starttime { get; set; }
	    public virtual string sleep_endtime { get; set; }
	    public virtual string remote_aspx { get; set; }
	    public virtual string status_1 { get; set; }
	    public virtual string status_2 { get; set; }
	    public virtual string status_3 { get; set; }
	    public virtual string status_4 { get; set; }
	    public virtual string status_5 { get; set; }
	    public virtual string status_6 { get; set; }
	}

    /// <summary>
    /// A class which represents the by_sms_template table.
    /// </summary>
	[Table("by_sms_template")]
	public partial class bysmstemplate
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int id { get; set; }
	    public virtual string title { get; set; }
	    public virtual string call_index { get; set; }
	    public virtual string call_content { get; set; }
	    public virtual byte? is_sys { get; set; }
	    public virtual string field_1 { get; set; }
	    public virtual string field_2 { get; set; }
	}

    /// <summary>
    /// A class which represents the by_etor_company table.
    /// </summary>
	[Table("by_etor_company")]
	public partial class byetorcompany
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int id { get; set; }
	    public virtual int? etor_id { get; set; }
	    public virtual byte? company_type { get; set; }
	    public virtual string company_name { get; set; }
	    public virtual string company_manager { get; set; }
	    public virtual string company_managerphone { get; set; }
	    public virtual string field_1 { get; set; }
	    public virtual string field_2 { get; set; }
	}

    /// <summary>
    /// A class which represents the by_sim table.
    /// </summary>
	[Table("by_sim")]
	public partial class bysim
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int id { get; set; }
	    public virtual string sim_id { get; set; }
	    public virtual string imsi { get; set; }
	    public virtual string operators { get; set; }
	    public virtual DateTime? create_time { get; set; }
	    public virtual int? create_user { get; set; }
	    public virtual string field_1 { get; set; }
	    public virtual string field_2 { get; set; }
	}

    /// <summary>
    /// A class which represents the by_v_etor_checked_detail view.
    /// </summary>
	[Table("by_v_etor_checked_detail")]
	public partial class byvetorcheckeddetail
	{
	    public virtual int id { get; set; }
	    public virtual int etor_id { get; set; }
	    public virtual byte? type { get; set; }
	    public virtual string start_time { get; set; }
	    public virtual string end_time { get; set; }
	    public virtual string field_1 { get; set; }
	    public virtual string field_2 { get; set; }
	    public virtual string etor_bianhao { get; set; }
	    public virtual int? dtu_id { get; set; }
	    public virtual int? etor_species_id { get; set; }
	    public virtual int? project_id { get; set; }
	    public virtual int? organize_id { get; set; }
	    public virtual string dizhi_code { get; set; }
	    public virtual string build_name { get; set; }
	    public virtual string build_number { get; set; }
	    public virtual string build_etorindex { get; set; }
	    public virtual string dizhi_detail { get; set; }
	    public virtual string zuobiao { get; set; }
	    public virtual string zhuban_code { get; set; }
	    public virtual string zhuban_version { get; set; }
	    public virtual DateTime? zhuban_version_time { get; set; }
	    public virtual string floorcount { get; set; }
	    public virtual string weibao_user { get; set; }
	    public virtual string weibao_userphone { get; set; }
	    public virtual string weibao_manager { get; set; }
	    public virtual string weibao_managerphone { get; set; }
	    public virtual string weibao_interval { get; set; }
	    public virtual string weibao_type { get; set; }
	    public virtual string nianjian_time { get; set; }
	    public virtual string use_place { get; set; }
	    public virtual string brand_id { get; set; }
	    public virtual string etor_model { get; set; }
	    public virtual string product_model { get; set; }
	    public virtual string dtu_bianhao { get; set; }
	    public virtual byte? status { get; set; }
	    public virtual DateTime? status_time { get; set; }
	    public virtual string version { get; set; }
	    public virtual DateTime? veision_time { get; set; }
	    public virtual string rssi { get; set; }
	    public virtual DateTime? rssi_time { get; set; }
	    public virtual string ip { get; set; }
	    public virtual DateTime? lastactive_time { get; set; }
	    public virtual string imei { get; set; }
	    public virtual string imsi { get; set; }
	    public virtual string sim { get; set; }
	    public virtual byte? is_statusAsk { get; set; }
	    public virtual DateTime? statusAsk_endtime { get; set; }
	    public virtual int? heartbeat_interval { get; set; }
	    public virtual string server_ip { get; set; }
	    public virtual string server_port_canny { get; set; }
	    public virtual string server_port_byline { get; set; }
	    public virtual string project_bianhao { get; set; }
	    public virtual string project_name { get; set; }
	}

    /// <summary>
    /// A class which represents the by_etor_dtu_log table.
    /// </summary>
	[Table("by_etor_dtu_log")]
	public partial class byetordtulog
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int id { get; set; }
	    public virtual int? etor_id { get; set; }
	    public virtual string dtu_bianhao { get; set; }
	    public virtual DateTime? create_time { get; set; }
	    public virtual int? create_userid { get; set; }
	    public virtual string field_1 { get; set; }
	    public virtual string field_2 { get; set; }
	}

    /// <summary>
    /// A class which represents the by_v_etor_command_detail view.
    /// </summary>
	[Table("by_v_etor_command_detail")]
	public partial class byvetorcommanddetail
	{
	    public virtual int id { get; set; }
	    public virtual int? etor_id { get; set; }
	    public virtual int? dtu_id { get; set; }
	    public virtual string cmd_code { get; set; }
	    public virtual string cmd_name { get; set; }
	    public virtual int? create_userid { get; set; }
	    public virtual string cmd_request { get; set; }
	    public virtual string cmd_requesttime { get; set; }
	    public virtual string cmd_response { get; set; }
	    public virtual string cmd_response2 { get; set; }
	    public virtual string cmd_responsetime { get; set; }
	    public virtual byte? cmd_status { get; set; }
	    public virtual DateTime? create_time { get; set; }
	    public virtual string field_1 { get; set; }
	    public virtual string field_2 { get; set; }
	    public virtual string field_3 { get; set; }
	    public virtual string dtu_bianhao { get; set; }
	    public virtual byte status { get; set; }
	    public virtual DateTime? status_time { get; set; }
	    public virtual string version { get; set; }
	    public virtual DateTime? veision_time { get; set; }
	    public virtual string rssi { get; set; }
	    public virtual DateTime? rssi_time { get; set; }
	    public virtual string ip { get; set; }
	    public virtual DateTime? lastactive_time { get; set; }
	    public virtual string imei { get; set; }
	    public virtual string imsi { get; set; }
	    public virtual string sim { get; set; }
	    public virtual byte? is_statusAsk { get; set; }
	    public virtual DateTime? statusAsk_endtime { get; set; }
	    public virtual int? heartbeat_interval { get; set; }
	    public virtual string server_ip { get; set; }
	    public virtual string server_port_canny { get; set; }
	    public virtual string server_port_byline { get; set; }
	    public virtual string etor_bianhao { get; set; }
	    public virtual int? etor_species_id { get; set; }
	    public virtual int? project_id { get; set; }
	    public virtual int? organize_id { get; set; }
	    public virtual string dizhi_code { get; set; }
	    public virtual string build_name { get; set; }
	    public virtual string build_number { get; set; }
	    public virtual string build_etorindex { get; set; }
	    public virtual string dizhi_detail { get; set; }
	    public virtual string zuobiao { get; set; }
	    public virtual string zhuban_code { get; set; }
	    public virtual string zhuban_version { get; set; }
	    public virtual DateTime? zhuban_version_time { get; set; }
	    public virtual string floorcount { get; set; }
	    public virtual string weibao_user { get; set; }
	    public virtual string weibao_userphone { get; set; }
	    public virtual string weibao_manager { get; set; }
	    public virtual string weibao_managerphone { get; set; }
	    public virtual string weibao_interval { get; set; }
	    public virtual string weibao_type { get; set; }
	    public virtual string nianjian_time { get; set; }
	    public virtual string use_place { get; set; }
	    public virtual string brand_id { get; set; }
	    public virtual string etor_model { get; set; }
	    public virtual string product_model { get; set; }
	}

    /// <summary>
    /// A class which represents the by_citys table.
    /// </summary>
	[Table("by_citys")]
	public partial class bycity
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int id { get; set; }
	    public virtual string bianhao { get; set; }
	    public virtual string parent_bianhao { get; set; }
	    public virtual string name { get; set; }
	    public virtual int? sort_id { get; set; }
	    public virtual string zuobiao_center { get; set; }
	    public virtual string zuobiao_area { get; set; }
	    public virtual string field_1 { get; set; }
	    public virtual string field_2 { get; set; }
	}

    /// <summary>
    /// A class which represents the by_dtu_imsi_log table.
    /// </summary>
	[Table("by_dtu_imsi_log")]
	public partial class bydtuimsilog
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int id { get; set; }
	    public virtual int dtu_id { get; set; }
	    public virtual string imsi { get; set; }
	    public virtual DateTime? create_time { get; set; }
	    public virtual int? create_userid { get; set; }
	    public virtual string field_1 { get; set; }
	    public virtual string field_2 { get; set; }
	}

    /// <summary>
    /// A class which represents the by_etor_attribute table.
    /// </summary>
	[Table("by_etor_attribute")]
	public partial class byetorattribute
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int id { get; set; }
	    public virtual int etor_id { get; set; }
	    public virtual string attr_name { get; set; }
	    public virtual string attr_value { get; set; }
	    public virtual string field_1 { get; set; }
	    public virtual string field_2 { get; set; }
	}

    /// <summary>
    /// A class which represents the by_etor_checked table.
    /// </summary>
	[Table("by_etor_checked")]
	public partial class byetorchecked
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int id { get; set; }
	    public virtual int etor_id { get; set; }
	    public virtual byte? type { get; set; }
	    public virtual string start_time { get; set; }
	    public virtual string end_time { get; set; }
	    public virtual string field_1 { get; set; }
	    public virtual string field_2 { get; set; }
	}

    /// <summary>
    /// A class which represents the by_etor_event table.
    /// </summary>
	[Table("by_etor_event")]
	public partial class byetorevent
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int id { get; set; }
	    public virtual int etor_id { get; set; }
	    public virtual string dtu_bianhao { get; set; }
	    public virtual string event_code { get; set; }
	    public virtual string event_content { get; set; }
	    public virtual DateTime? create_time { get; set; }
	    public virtual string field_1 { get; set; }
	    public virtual string field_2 { get; set; }
	}

    /// <summary>
    /// A class which represents the by_project table.
    /// </summary>
	[Table("by_project")]
	public partial class byproject
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int id { get; set; }
	    public virtual string bianhao { get; set; }
	    public virtual string name { get; set; }
	    public virtual DateTime? reg_time { get; set; }
	    public virtual DateTime? checked_time { get; set; }
	    public virtual string manager { get; set; }
	    public virtual string manager_phone { get; set; }
	    public virtual string dizhi_code { get; set; }
	    public virtual string dizhi_detail { get; set; }
	    public virtual DateTime? create_time { get; set; }
	    public virtual int? create_userid { get; set; }
	    public virtual string sleep_starttime { get; set; }
	    public virtual string sleep_endtime { get; set; }
	    public virtual string field_1 { get; set; }
	    public virtual string field_2 { get; set; }
	}

    /// <summary>
    /// A class which represents the by_v_user_etor view.
    /// </summary>
	[Table("by_v_user_etor")]
	public partial class byvuseretor
	{
	    public virtual int? user_id { get; set; }
	    public virtual int? dtu_id { get; set; }
	}

    /// <summary>
    /// A class which represents the by_v_loginlog_detail view.
    /// </summary>
	[Table("by_v_loginlog_detail")]
	public partial class byvloginlogdetail
	{
	    public virtual int id { get; set; }
	    public virtual string account { get; set; }
	    public virtual string status { get; set; }
	    public virtual string ip_address { get; set; }
	    public virtual string mac_address { get; set; }
	    public virtual string login_device { get; set; }
	    public virtual string browser_version { get; set; }
	    public virtual DateTime? create_time { get; set; }
	    public virtual string field_1 { get; set; }
	    public virtual string field_2 { get; set; }
	    public virtual int user_id { get; set; }
	    public virtual string bianhao { get; set; }
	    public virtual string pwd { get; set; }
	    public virtual string secre_key { get; set; }
	    public virtual byte? user_type { get; set; }
	    public virtual string realname { get; set; }
	    public virtual string realname_spell { get; set; }
	    public virtual string sub_name { get; set; }
	    public virtual int? role_id { get; set; }
	    public virtual int? organize_id { get; set; }
	    public virtual byte? sex { get; set; }
	    public virtual string title { get; set; }
	    public virtual string email { get; set; }
	    public virtual string phone { get; set; }
	    public virtual string caption { get; set; }
	    public virtual byte? enabled { get; set; }
	    public virtual byte? single_login { get; set; }
	    public virtual byte? mobile_login { get; set; }
	    public virtual byte? is_limitip { get; set; }
	    public virtual byte? is_alarm { get; set; }
	    public virtual byte? is_sys { get; set; }
	    public virtual DateTime? user_create_time { get; set; }
	    public virtual int? create_userid { get; set; }
	    public virtual string remark { get; set; }
	    public virtual string user_field_1 { get; set; }
	    public virtual string user_field_2 { get; set; }
	    public virtual string user_field_3 { get; set; }
	}

    /// <summary>
    /// A class which represents the by_etor_tickets_fault table.
    /// </summary>
	[Table("by_etor_tickets_fault")]
	public partial class byetorticketsfault
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int id { get; set; }
	    public virtual int? etor_tickets_id { get; set; }
	    public virtual int? etor_id { get; set; }
	    public virtual string dtu_bianhao { get; set; }
	    public virtual string master_code { get; set; }
	    public virtual string second_code { get; set; }
	    public virtual string fault_speed { get; set; }
	    public virtual string fault_floor { get; set; }
	    public virtual string fault_datetime { get; set; }
	    public virtual string fault_content { get; set; }
	    public virtual string remark { get; set; }
	    public virtual DateTime? create_time { get; set; }
	    public virtual string field_1 { get; set; }
	    public virtual string field_2 { get; set; }
	    public virtual string field_3 { get; set; }
	    public virtual string field_4 { get; set; }
	    public virtual string field_5 { get; set; }
	}

    /// <summary>
    /// A class which represents the by_etor_tickets_steps table.
    /// </summary>
	[Table("by_etor_tickets_steps")]
	public partial class byetorticketsstep
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int id { get; set; }
	    public virtual int? etor_tickets_id { get; set; }
	    public virtual byte? step_index { get; set; }
	    public virtual string step_name { get; set; }
	    public virtual byte? step_status { get; set; }
	    public virtual string step_time { get; set; }
	    public virtual string field_1 { get; set; }
	    public virtual string field_2 { get; set; }
	}

    /// <summary>
    /// A class which represents the by_operation_log table.
    /// </summary>
	[Table("by_operation_log")]
	public partial class byoperationlog
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int id { get; set; }
	    public virtual string operation_account { get; set; }
	    public virtual string operation_name { get; set; }
	    public virtual string table_name { get; set; }
	    public virtual string business_name { get; set; }
	    public virtual string table_id { get; set; }
	    public virtual string operation_ip { get; set; }
	    public virtual string remark { get; set; }
	    public virtual DateTime? create_time { get; set; }
	    public virtual string field_1 { get; set; }
	    public virtual string field_2 { get; set; }
	}

    /// <summary>
    /// A class which represents the by_v_etor_detail view.
    /// </summary>
	[Table("by_v_etor_detail")]
	public partial class byvetordetail
	{
	    public virtual int id { get; set; }
	    public virtual string bianhao { get; set; }
	    public virtual int dtu_id { get; set; }
	    public virtual int? etor_species_id { get; set; }
	    public virtual int? project_id { get; set; }
	    public virtual int? organize_id { get; set; }
	    public virtual string dizhi_code { get; set; }
	    public virtual string build_name { get; set; }
	    public virtual string build_number { get; set; }
	    public virtual string build_etorindex { get; set; }
	    public virtual string dizhi_detail { get; set; }
	    public virtual string zuobiao { get; set; }
	    public virtual string zhuban_code { get; set; }
	    public virtual string zhuban_version { get; set; }
	    public virtual DateTime? zhuban_version_time { get; set; }
	    public virtual string floorcount { get; set; }
	    public virtual string weibao_user { get; set; }
	    public virtual string weibao_userphone { get; set; }
	    public virtual string weibao_manager { get; set; }
	    public virtual string weibao_managerphone { get; set; }
	    public virtual string weibao_interval { get; set; }
	    public virtual string weibao_type { get; set; }
	    public virtual string nianjian_time { get; set; }
	    public virtual string use_place { get; set; }
	    public virtual string brand_id { get; set; }
	    public virtual string etor_model { get; set; }
	    public virtual string product_model { get; set; }
	    public virtual int? create_userid { get; set; }
	    public virtual DateTime? create_time { get; set; }
	    public virtual string dtu_bianhao { get; set; }
	    public virtual byte? status { get; set; }
	    public virtual DateTime? status_time { get; set; }
	    public virtual string version { get; set; }
	    public virtual DateTime? veision_time { get; set; }
	    public virtual string rssi { get; set; }
	    public virtual DateTime? rssi_time { get; set; }
	    public virtual string ip { get; set; }
	    public virtual DateTime? lastactive_time { get; set; }
	    public virtual string imei { get; set; }
	    public virtual string imsi { get; set; }
	    public virtual string sim { get; set; }
	    public virtual DateTime? dtu_create_time { get; set; }
	    public virtual byte? is_statusAsk { get; set; }
	    public virtual DateTime? statusAsk_endtime { get; set; }
	    public virtual int? heartbeat_interval { get; set; }
	    public virtual string etor_species_code { get; set; }
	    public virtual string caption { get; set; }
	    public virtual byte? etor_type { get; set; }
	    public virtual string etor_default_img { get; set; }
	    public virtual string remote_aspx { get; set; }
	    public virtual string fault_index_depth { get; set; }
	    public virtual string mask_format { get; set; }
	    public virtual string project_bianhao { get; set; }
	    public virtual string project_name { get; set; }
	    public virtual string organize_bianhao { get; set; }
	    public virtual string organize_name { get; set; }
	}

    /// <summary>
    /// A class which represents the by_etor_command table.
    /// </summary>
	[Table("by_etor_command")]
	public partial class byetorcommand
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int id { get; set; }
	    public virtual int? etor_id { get; set; }
	    public virtual int? dtu_id { get; set; }
	    public virtual string cmd_code { get; set; }
	    public virtual string cmd_name { get; set; }
	    public virtual int? create_userid { get; set; }
	    public virtual string cmd_request { get; set; }
	    public virtual string cmd_requesttime { get; set; }
	    public virtual string cmd_response { get; set; }
	    public virtual string cmd_response2 { get; set; }
	    public virtual string cmd_responsetime { get; set; }
	    public virtual byte? cmd_status { get; set; }
	    public virtual DateTime? create_time { get; set; }
	    public virtual string field_1 { get; set; }
	    public virtual string field_2 { get; set; }
	    public virtual string field_3 { get; set; }
	}

    /// <summary>
    /// A class which represents the by_role table.
    /// </summary>
	[Table("by_role")]
	public partial class byrole
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int id { get; set; }
	    public virtual int? organize_id { get; set; }
	    public virtual int? parent_id { get; set; }
	    public virtual string bianhao { get; set; }
	    public virtual string name { get; set; }
	    public virtual string role_type { get; set; }
	    public virtual string caption { get; set; }
	    public virtual byte? has_edit { get; set; }
	    public virtual byte? has_delete { get; set; }
	    public virtual byte? enabled { get; set; }
	    public virtual int? sort_id { get; set; }
	    public virtual DateTime? create_time { get; set; }
	    public virtual int? create_userid { get; set; }
	    public virtual string field_1 { get; set; }
	    public virtual string field_2 { get; set; }
	}

    /// <summary>
    /// A class which represents the by_etor table.
    /// </summary>
	[Table("by_etor")]
	public partial class byetor
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int id { get; set; }
	    public virtual string bianhao { get; set; }
	    public virtual int dtu_id { get; set; }
	    public virtual int? etor_species_id { get; set; }
	    public virtual int? project_id { get; set; }
	    public virtual int? organize_id { get; set; }
	    public virtual string dizhi_code { get; set; }
	    public virtual string build_name { get; set; }
	    public virtual string build_number { get; set; }
	    public virtual string build_etorindex { get; set; }
	    public virtual string dizhi_detail { get; set; }
	    public virtual string zuobiao { get; set; }
	    public virtual string zhuban_code { get; set; }
	    public virtual string zhuban_version { get; set; }
	    public virtual DateTime? zhuban_version_time { get; set; }
	    public virtual string floorcount { get; set; }
	    public virtual string weibao_user { get; set; }
	    public virtual string weibao_userphone { get; set; }
	    public virtual string weibao_manager { get; set; }
	    public virtual string weibao_managerphone { get; set; }
	    public virtual string weibao_interval { get; set; }
	    public virtual string weibao_type { get; set; }
	    public virtual string nianjian_time { get; set; }
	    public virtual string use_place { get; set; }
	    public virtual string brand_id { get; set; }
	    public virtual string etor_model { get; set; }
	    public virtual string product_model { get; set; }
	    public virtual DateTime? create_time { get; set; }
	    public virtual int? create_userid { get; set; }
	    public virtual string field_1 { get; set; }
	    public virtual string field_2 { get; set; }
	}

    /// <summary>
    /// A class which represents the by_etor_fault_config table.
    /// </summary>
	[Table("by_etor_fault_config")]
	public partial class byetorfaultconfig
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int id { get; set; }
	    public virtual int? etor_species_id { get; set; }
	    public virtual string fault_code { get; set; }
	    public virtual string fault_display_code { get; set; }
	    public virtual string fault_desc { get; set; }
	    public virtual string fault_desc_en { get; set; }
	    public virtual byte? is_alarm { get; set; }
	    public virtual int? sms_delay { get; set; }
	    public virtual string sms_desc { get; set; }
	    public virtual string sms_desc_en { get; set; }
	    public virtual string type { get; set; }
	    public virtual string levels { get; set; }
	    public virtual string sleep_starttime { get; set; }
	    public virtual string sleep_endtime { get; set; }
	    public virtual string field_1 { get; set; }
	    public virtual string field_2 { get; set; }
	}

    /// <summary>
    /// A class which represents the by_v_etor_tickets_steps view.
    /// </summary>
	[Table("by_v_etor_tickets_steps")]
	public partial class byvetorticketsstep
	{
	    public virtual int? etor_tickets_id { get; set; }
	    public virtual string 已接收 { get; set; }
	    public virtual string 已报警 { get; set; }
	    public virtual string 已接警 { get; set; }
	    public virtual string 已到场 { get; set; }
	    public virtual string 已完工 { get; set; }
	    public virtual string 已确认 { get; set; }
	}

    /// <summary>
    /// A class which represents the by_menu table.
    /// </summary>
	[Table("by_menu")]
	public partial class bymenu
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int id { get; set; }
	    public virtual int parent_id { get; set; }
	    public virtual byte? nav_type { get; set; }
	    public virtual string name { get; set; }
	    public virtual string sub_name { get; set; }
	    public virtual string caption { get; set; }
	    public virtual string link_url { get; set; }
	    public virtual string link_target { get; set; }
	    public virtual int? sort_id { get; set; }
	    public virtual byte? enabled { get; set; }
	    public virtual string css_class { get; set; }
	    public virtual string action_list { get; set; }
	    public virtual byte? class_layer { get; set; }
	    public virtual byte? is_open { get; set; }
	    public virtual byte? is_sys { get; set; }
	    public virtual DateTime? create_time { get; set; }
	    public virtual string form_name { get; set; }
	    public virtual byte? has_edit { get; set; }
	    public virtual byte? has_delete { get; set; }
	    public virtual string field_1 { get; set; }
	    public virtual string field_2 { get; set; }
	}

    /// <summary>
    /// A class which represents the by_etor_tickets_sms table.
    /// </summary>
	[Table("by_etor_tickets_sms")]
	public partial class byetorticketssm
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int id { get; set; }
	    public virtual int? etor_tickets_id { get; set; }
	    public virtual byte? type { get; set; }
	    public virtual string emp_name { get; set; }
	    public virtual string emp_phone { get; set; }
	    public virtual string sms_content { get; set; }
	    public virtual DateTime? create_time { get; set; }
	    public virtual string field_1 { get; set; }
	    public virtual string field_2 { get; set; }
	}

    /// <summary>
    /// A class which represents the by_button table.
    /// </summary>
	[Table("by_button")]
	public partial class bybutton
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int id { get; set; }
	    public virtual string name { get; set; }
	    public virtual string icon { get; set; }
	    public virtual string css_class { get; set; }
	    public virtual string btn_event { get; set; }
	    public virtual string control_id { get; set; }
	    public virtual string type { get; set; }
	    public virtual byte? split { get; set; }
	    public virtual string caption { get; set; }
	    public virtual byte? enabled { get; set; }
	    public virtual int? paixu { get; set; }
	    public virtual DateTime? create_time { get; set; }
	    public virtual int? create_userid { get; set; }
	    public virtual string field_1 { get; set; }
	    public virtual string field_2 { get; set; }
	}

    /// <summary>
    /// A class which represents the by_role_menu table.
    /// </summary>
	[Table("by_role_menu")]
	public partial class byrolemenu
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int id { get; set; }
	    public virtual int? role_id { get; set; }
	    public virtual int? menu_id { get; set; }
	    public virtual DateTime? create_time { get; set; }
	    public virtual int? create_userid { get; set; }
	    public virtual string field_1 { get; set; }
	    public virtual string field_2 { get; set; }
	}

    /// <summary>
    /// A class which represents the by_v_role_menu view.
    /// </summary>
	[Table("by_v_role_menu")]
	public partial class byvrolemenu
	{
	    public virtual int? role_id { get; set; }
	    public virtual int id { get; set; }
	    public virtual int parent_id { get; set; }
	    public virtual byte? nav_type { get; set; }
	    public virtual string name { get; set; }
	    public virtual string sub_name { get; set; }
	    public virtual string caption { get; set; }
	    public virtual string link_url { get; set; }
	    public virtual string link_target { get; set; }
	    public virtual int? sort_id { get; set; }
	    public virtual byte? enabled { get; set; }
	    public virtual string css_class { get; set; }
	    public virtual string action_list { get; set; }
	    public virtual byte? class_layer { get; set; }
	    public virtual byte? is_open { get; set; }
	    public virtual byte? is_sys { get; set; }
	    public virtual DateTime? create_time { get; set; }
	    public virtual string form_name { get; set; }
	    public virtual byte? has_edit { get; set; }
	    public virtual byte? has_delete { get; set; }
	    public virtual string field_1 { get; set; }
	    public virtual string field_2 { get; set; }
	}

    /// <summary>
    /// A class which represents the by_menu_button table.
    /// </summary>
	[Table("by_menu_button")]
	public partial class bymenubutton
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int id { get; set; }
	    public virtual int? menu_id { get; set; }
	    public virtual int? button_id { get; set; }
	    public virtual int? sort_id { get; set; }
	    public virtual DateTime? create_time { get; set; }
	    public virtual int? create_userid { get; set; }
	    public virtual string field_1 { get; set; }
	    public virtual string field_2 { get; set; }
	}

    /// <summary>
    /// A class which represents the by_role_menu_button table.
    /// </summary>
	[Table("by_role_menu_button")]
	public partial class byrolemenubutton
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int id { get; set; }
	    public virtual int role_id { get; set; }
	    public virtual int menu_id { get; set; }
	    public virtual int button_id { get; set; }
	    public virtual DateTime? create_time { get; set; }
	    public virtual int? create_userid { get; set; }
	    public virtual string field_1 { get; set; }
	    public virtual string field_2 { get; set; }
	}

    /// <summary>
    /// A class which represents the by_etor_runstatus table.
    /// </summary>
	[Table("by_etor_runstatus")]
	public partial class byetorrunstatu
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int id { get; set; }
	    public virtual int etor_id { get; set; }
	    public virtual string status_name { get; set; }
	    public virtual string status_value { get; set; }
	    public virtual string field_1 { get; set; }
	    public virtual string field_2 { get; set; }
	}

    /// <summary>
    /// A class which represents the by_etor_tickets table.
    /// </summary>
	[Table("by_etor_tickets")]
	public partial class byetorticket
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	    public virtual int id { get; set; }
	    public virtual int? etor_id { get; set; }
	    public virtual string bianhao { get; set; }
	    public virtual int? status { get; set; }
	    public virtual int? type { get; set; }
	    public virtual int? call_user { get; set; }
	    public virtual string call_content { get; set; }
	    public virtual string call_type { get; set; }
	    public virtual string receive_user { get; set; }
	    public virtual string receive_userphone { get; set; }
	    public virtual DateTime? create_time { get; set; }
	    public virtual string remark { get; set; }
	    public virtual byte? is_inspection { get; set; }
	    public virtual string field_1 { get; set; }
	    public virtual string field_2 { get; set; }
	}

    /// <summary>
    /// A class which represents the user table.
    /// </summary>
	[Table("user")]
	public partial class user
	{
	    public virtual string name { get; set; }
	    public virtual int? age { get; set; }
	    public virtual string title { get; set; }
	}

}

